### PR TITLE
Surround __file__ with quotation marks

### PR DESCRIPTION
**Pull request by weizmannk**
Without  ' '  on __file__ I get : NameError: name '__file__' is not defined

### CODE REVIEW

**Comment by weizmannk** [comment]
Hi Theo, 
On my side when there no ' ' around __file__ , I got an error, 
but with that the run is ok. 
So could you please check if this is the same thing by your side . 
Thanks

**Comment by Theodlz** [comment]
Hi @weizmannk ! Thanks for the pull request. I'll have a look at it tonight or tomorrow morning.

**Comment by Theodlz** [comment]
Hi @weizmannk, upon further research, in Python, `__file__` is a variable that indicates the path to the file being executed and/or imported. Therefore, as it is a variable's name, and not a simple string, it shouldn't need quotation marks. I'm investigating why you would need one but not me. The code runs both locally and on the GitHub actions without it, which is why i'm puzzled by all this. I'll try to see if it has anything to do with which version of python we're using.

**Comment by Theodlz** [comment]
Also, did you get an error running the code of skyportal-fink-client, or just when reusing that bit of code in your own code ?

**Comment by Theodlz** [comment]
My guess is that when using quotation marks its actually ignored, and acts like a `os.getcwd()`

**Comment by Theodlz** [comment]
If that's the case, we need to think about replacing that bit of code entirely to do it differently.

**Comment by weizmannk** [comment]
Hi Theo,  
When I run  skyportal-fink-client, I got this error, with or without  ' ', on __file__ 
ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/taxonomy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f005b417fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))


I focused on the bits of code that interested me more. 
Maybe the ideal is to compile the whole code. 
Yes that's exactly it, when I add the ' ' it behaves like os.getcwd(), I even thought that's what you're trying to do?

**Comment by Theodlz** [comment]
> Hi Theo, When I run skyportal-fink-client, I got this error, with or without ' ', on **file** ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/taxonomy (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f005b417fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> I focused on the bits of code that interested me more. Maybe the ideal is to compile the whole code. Yes that's exactly it, when I add the ' ' it behaves like os.getcwd(), I even thought that's what you're trying to do?

Ok, but that error is something else. As skyportal-fink-client aims to push data to skyportal, did you give the url and token of a running instance of SkyPortal ? You can run it locally and use localhost when in development, but if it can't access to SkyPortal, you'll get this kind of error. You'll get this too if the token is invalid. I'll add something a bit more robust to avoid errors. 

But my question was how did you run the bit of code you modified, how did you get the error related to `__file__` ? I would need an example so i can reproduce it ! Otherwise it can't have a look at the problem.

**Comment by Theodlz** [comment]
So @weizmannk i have the answer ! The `__file__` is created by python when the code is imported as a module. So here, it is correct and it works as that is what's happening.

**Comment by weizmannk** [comment]
Hi Theo, ok , 
About what I run :


import os
import utils.files as files
conf = files.yaml_to_dict(
    os.path.abspath(os.path.join(os.path.dirname(__file__))) + "/../config.yaml"
)

**Comment by weizmannk** [comment]
Ah! Ok , i see, so I understand why this didn't work for my side, 
So I need to run it as module .

Thanks for these explanations

**Pull request closed without merging**
